nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"] # Or your frontend URL: ['https://your-frontend.com']
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    max_age: 3600
  paths:
    "^/": # Apply to all routes
      origin_regex: true
      allow_origin: ["*"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      max_age: 3600
      allow_credentials: true
